### ISSUE TITLE
Criar formulário principal

### ISSUE THREAD

**Issue by clevertonh** [clevertonh/paa-projeto-2015b#4]
Criar o formulário principal, utilizando o MDI.

**Comment by clevertonh** [comment]
Foi criado o formulário principal, coloquei os controles para utilizar o MDI.

Rodrigo, acha que precisa mais alguma coisa nessa tela?

**Comment by roliveira059** [comment]
Poderíamos criar alguns ícones como favoritos, para facilitar o acesso as funções.

**Comment by roliveira059** [comment]
Cléverton, acabei desabilitando o controle para não permitir fechar a janela principal sem as demais estarem fechadas, tu lembra como faz para habilitar novamente?

**Comment by clevertonh** [comment]
vou dar uma olhada, dai te aviso

Em 9 de setembro de 2015 03:53, roliveira059 <notifications@github.com>
escreveu:

> Cléverton, acabei desabilitando o controle para não permitir fechar a
> janela principal sem as demais estarem fechadas, tu lembra como faz para
> habilitar novamente?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clevertonh/paa-projeto-2015b/issues/4#issuecomment-138806908>
> .
>



-- 
att,
Cléverton Heming

**Comment by clevertonh** [comment]
Criado
